## Decision tree (Cây quyết định)
- Mục đích là để đưa ra dự đoán trên dữ liệu có tính liên tục không rời rạc từng điểm. 
- Cây quyết định sẽ lựa chọn hướng phân loại theo chỉ số Gini Impurity nến cần gần 0.0 thì độ chính xác càng cao.
### Làm ví dụ phân loại chuột để hiểu rõ hơn .

In [1]:
#Import library and create data.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

1. Tạo dữ liệu chuột (Mice Dataset)
Đoạn code dưới đây sẽ tạo ra một file Mice_Dataset.csv với 100 con chuột, bao gồm các đặc trưng:

Weight_g: Trọng lượng (gam)

Length_cm: Chiều dài (cm)

Tail_Length_cm: Chiều dài đuôi (cm)

Fur_Color: Màu lông (Đen, Trắng, Nâu, Xám)

Diet: Chế độ ăn (Standard - Tiêu chuẩn, High-Fat - Nhiều chất béo)

Healthy: Nhãn phân loại (1 = Khỏe mạnh, 0 = Không khỏe mạnh)

In [11]:
np.random.seed(42)
n_samples = 10

data = {
    'Weight_g': np.random.normal(loc=25, scale=5, size=n_samples), 
    'Length_cm': np.random.normal(loc=10, scale=2, size=n_samples), 
    'Tail_Length_cm': np.random.normal(loc=8, scale=1.5, size=n_samples), 
    'Fur_Color': np.random.choice(['Black', 'White', 'Brown', 'Gray'], size=n_samples), 
    'Diet': np.random.choice(['Standard', 'High-Fat'], size=n_samples) 
}

df_mice = pd.DataFrame(data)
display(df_mice.head(10))

    Weight_g  Length_cm  Tail_Length_cm Fur_Color      Diet
0  27.483571   9.073165       10.198473      Gray  High-Fat
1  24.308678   9.068540        7.661336      Gray  Standard
2  28.238443  10.483925        8.101292     Brown  High-Fat
3  32.615149   6.173440        5.862878      Gray  High-Fat
4  23.829233   6.550164        7.183426     Brown  High-Fat
5  23.829315   8.875425        8.166384      Gray  High-Fat
6  32.896064   7.974338        6.273510     Black  High-Fat
7  28.837174  10.628495        8.563547      Gray  High-Fat
8  22.652628   8.183952        7.099042     Brown  High-Fat
9  27.712800   7.175393        7.562459     Brown  High-Fat

In [13]:
# phan loai suc khoe
def determine_health(row):
    is_healthy = 1
    if row['Weight_g'] < 18 or row['Weight_g'] > 32:
        is_healthy = 0
    if row['Length_cm']/row['Tail_Length_cm']>1.5:
        is_healthy = 0
    
    #make noise
    if np.random.rand()<0.1:
        is_healthy = 1 - is_healthy
    return is_healthy

df_mice['Healthy'] = df_mice.apply(determine_health, axis= 1)
df_mice

    Weight_g  Length_cm  Tail_Length_cm Fur_Color      Diet  Healthy
0  27.483571   9.073165       10.198473      Gray  High-Fat        0
1  24.308678   9.068540        7.661336      Gray  Standard        1
2  28.238443  10.483925        8.101292     Brown  High-Fat        1
3  32.615149   6.173440        5.862878      Gray  High-Fat        0
4  23.829233   6.550164        7.183426     Brown  High-Fat        1
5  23.829315   8.875425        8.166384      Gray  High-Fat        1
6  32.896064   7.974338        6.273510     Black  High-Fat        0
7  28.837174  10.628495        8.563547      Gray  High-Fat        1
8  22.652628   8.183952        7.099042     Brown  High-Fat        1
9  27.712800   7.175393        7.562459     Brown  High-Fat        1

In [ ]:
# Xu ly tien du lieu
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_mice['Fur_Color_Encoded']

In [ ]:
# Xay dung cay quyet dinh
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(max_depth= 3, random_state=42) # gioi han do sau
clf.fit